### ISSUE TITLE
Partner Fixing Group 1

### ISSUE THREAD

**Issue by AndrewCerveny** [KarimAl-Rashdan/fitlit#15]
- [x]  **As a developer** my class names need to be consistent ex Sleep-Class.js --> Sleep.js
- [x]  **As a developer** my (.catch of fetch \ post) should be displayed to Dom: so a user can know something is wrong.
- [x]  **As a developer** returnToSleepWidget & returnToStepsWidget should be refactored to one function.
- [ ]  **As a developer** calcuateSleepByDate() what if a date is not placed in...
- [x]  **As a developer** : indentions again 77-83 of HyrdroRepo-test.js
- [x]  **As a User my data** should display as "01/11/2020:2.3 , 01/12/2020: 2.1 currently it is day1:2.3, day2:2.1

**Comment by BHaddad1** [comment]
We are going to do sad path testing together.

**Comment by AndrewCerveny** [comment]
Doing sad path together all other issues has been worked on and has their own pull request.
